---
version: 1

kind: experiment

framework: pytorch

environment:
  resources:
    gpu:
      requests: 1
      limits: 1
    cpu:
      requests: 2
      limits: 2

params:
  epochs: 100
  learning_rate: 1
  batch_size: 1000

logging:
  level: INFO

build:
  image: pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime
  build_steps:
    - pip install --no-cache-dir -U polyaxon-client[gcs]==0.6.1
    - pip install tensorboard

run:
  cmd: python model.py --epochs={{ epochs }}\
         --lr={{ learning_rate }} \
         --batch-size={{ batch_size }} \
         --test-batch-size={{ batch_size }}